export const PILLARS: Record<string, string[]> = {
  Relacionamentos: [
    'Eu sou eu mesma(o) nessa relação?',
    'Há confiança genuína?',
    'Sinto que essa relação me nutre emocionalmente?',
    'Consigo expressar minhas necessidades sem medo?',
    'Sinto que há reciprocidade no esforço pela relação?',
    'Respeitamos os limites um do outro?',
    'Temos momentos de qualidade juntos?',
    'Sinto que crescemos juntos?',
  ],
  'Vida Profissional': [
    'Meu trabalho contribui para meu propósito?',
    'Meu ambiente de trabalho é saudável e não tóxico?',
    'Sinto-me valorizado profissionalmente?',
    'Tenho perspectiva de crescimento?',
    'Meu trabalho está alinhado com meus valores?',
    'Consigo equilibrar trabalho e vida pessoal?',
    'Sinto orgulho do que faço?',
    'Minha remuneração é justa pelo que entrego?',
  ],
  'Vida Familiar': [
    'Consigo ser autêntico(a) com minha família?',
    'Minha família respeita minhas escolhas?',
    'Temos momentos de paz e harmonia?',
    'Sinto-me apoiado(a) nas minhas decisões?',
    'Há comunicação aberta e sem julgamentos?',
    'Consigo estabelecer limites saudáveis com eles?',
    'Perdoamos e resolvemos conflitos facilmente?',
    'Sinto que meu lar é meu refúgio?',
  ],
  'Relações Sociais': [
    'Tenho alguém que poderia chamar às 3h da manhã?',
    'Sinto-me conectado e não sinto solidão cercado de pessoas?',
    'Meus amigos me inspiram a ser melhor?',
    'Posso ser vulnerável com meus amigos?',
    'Participo de atividades em grupo com prazer?',
    'Sinto que pertenço a uma comunidade?',
    'Minhas amizades são baseadas em troca mútua?',
    'Consigo fazer novos amigos com facilidade?',
  ],
  Espiritualidade: [
    'Sinto que há um sentido claro para minha vida?',
    'Minha fé (ou crença) me capacita a agir?',
    'Tenho momentos de paz interior e reflexão?',
    'Sinto conexão com algo maior que eu mesmo?',
    'Pratico gratidão diariamente?',
    'Consigo encontrar propósito nas dificuldades?',
    'Minhas ações refletem minhas crenças mais profundas?',
    'Sinto esperança em relação ao futuro?',
  ],
  'Situação Financeira': [
    'Tenho clareza absoluta e sei exatamente quanto devo?',
    'Tenho reserva para emergências?',
    'Gasto menos do que ganho?',
    'Sinto que o dinheiro me dá liberdade de escolhas?',
    'Tenho um plano claro para minha aposentadoria/futuro?',
    'Invisto parte do meu dinheiro regularmente?',
    'Não sinto ansiedade constante por causa de dinheiro?',
    'Sinto que sou bem remunerado(a) pelo meu valor?',
  ],
  'Saúde Física e Mental': [
    'Durmo de 7 a 9 horas com qualidade?',
    'Me exercito regularmente?',
    'Minha alimentação é nutritiva e equilibrada?',
    'Consigo gerenciar meu estresse no dia a dia?',
    'Tenho energia e disposição para minhas tarefas?',
    'Faço exames preventivos regularmente?',
    'Dedico tempo para meu lazer e descanso mental?',
    'Sinto-me bem com meu corpo e minha mente?',
  ],
}
